#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then
    echo "could not find COSMOS install directory!";
    exit 1
fi

FOLDER="libdfp"

if [[ -d "$FOLDER" ]]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i clean || true
else
    # download the source code at a specific commit without downloading everything
    git init "$FOLDER" -q
    cd $FOLDER
    git remote add origin https://github.com/libdfp/libdfp.git
    git fetch origin 96a6edb07af44ca5b3c5600e0e662d6308c55fc6 --depth=1
    git reset --hard FETCH_HEAD

    # apply patches
    git apply ../cosmo.patch
fi

# TODO: Find a way to use superconfigure's local gcc build instead of the cosmopolitan shipped one
# to avoid having to copy it over, or at least automate that copy.

# configure
autoconf -f || true

./configure --disable-shared --enable-static\
    --prefix=$COSMOS\
    CFLAGS="-Os"

# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
