#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then
    echo "could not find COSMOS install directory!";
    exit 1
fi

# install prerequisite apegcc with --enable-decimal-float
# this should have already been built by make so just need to replace $COSMO's stock compiler
# TODO: Confirm this works for aarch64 and on Windows(does any of superconfigure work on Windows currently?)
if [[ ! -f "$COSMOS/bin/$ARCH-linux-cosmo-gcc" ]]; then
    echo "could not find apegcc in COSMOS";
    exit 1
fi

GCCBIN="$COSMO/o/$MODE/third_party/gcc/bin/"
GCCLIB="$COSMO/o/$MODE/third_party/gcc/libexec/gcc/$ARCH-linux-cosmo/11.2.0/"

rm -rf "$GCCBIN"* || true
mkdir -p "$GCCBIN" "$GCCLIB"
cp "$COSMOS/bin/$ARCH-linux-cosmo-"* "$GCCBIN"
find "$COSMOS/libexec/gcc/$ARCH-linux-cosmo/11.2.0/" -maxdepth 1 -type f -execdir cp "{}" "$GCCLIB" ";"
cp  "$COSMOS/$ARCH-linux-cosmo/bin/ld.bfd" "$GCCLIB"
chmod +x "$GCCBIN"* "$GCCLIB"*

FOLDER="libdfp/"

if [[ -d "$FOLDER" ]]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i clean || true
    make -s -i distclean || true
else
    # download the source code at a specific commit without downloading everything
    git init "$FOLDER" -q
    cd $FOLDER
    git remote add origin https://github.com/libdfp/libdfp.git
    git fetch origin 96a6edb07af44ca5b3c5600e0e662d6308c55fc6 --depth=1
    git reset --hard FETCH_HEAD

    # apply patches
    git apply ../cosmo.patch
fi

# run configure
autoconf -f

./configure --disable-shared --enable-static --prefix="$COSMOS"\
    CFLAGS="-Os"

# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
