#!/usr/bin/env bash
set -e

# check for cosmo dirs
if [ -z ${COSMO+x} ]; then
    echo "could not find COSMO source directory!";
    exit 1
fi

if [ -z ${COSMOS+x} ]; then
    echo "could not find COSMOS install directory!";
    exit 1
fi

# install prerequisite apegcc with --enable-decimal-float
# this should have already been built by make so just need to replace $COSMO's stock compiler
# TODO: Confirm this works for aarch64 and on Windows(does any of superconfigure work on Windows currently?)
if [[ ! -f "$COSMOS/bin/$ARCH-linux-cosmo-gcc" ]]; then
    echo "could not find apegcc in COSMOS";
    exit 1
fi

rm -rf "$COSMO/o/$MODE/third_party/gcc/bin/"* || true
mkdir -p "$COSMO/o/$MODE/third_party/gcc/bin" "$COSMO/o/$MODE/third_party/gcc/libexec/gcc/$ARCH-linux-cosmo/11.2.0/"
cp "$COSMOS/bin/$ARCH-linux-cosmo-"* "$COSMO/o/$MODE/third_party/gcc/bin/"
find "$COSMOS/libexec/gcc/$ARCH-linux-cosmo/11.2.0/" -maxdepth 1 -type f -execdir cp "{}" "$COSMO/o/$MODE/third_party/gcc/libexec/gcc/$ARCH-linux-cosmo/11.2.0/" ";"
cp  "$COSMOS/$ARCH-linux-cosmo/bin/ld"* "$COSMO/o/$MODE/third_party/gcc/libexec/gcc/$ARCH-linux-cosmo/11.2.0/"
chmod +x "$COSMO/o/$MODE/third_party/gcc/bin/"* "$COSMO/o/$MODE/third_party/gcc/libexec/gcc/$ARCH-linux-cosmo/11.2.0/"*

FOLDER="libdfp/"

if [[ -d "$FOLDER" ]]; then
    # we already downloaded it
    cd $FOLDER
    make -s -i clean || true
else
    # download the source code at a specific commit without downloading everything
    git init "$FOLDER" -q
    cd $FOLDER
    git remote add origin https://github.com/libdfp/libdfp.git
    git fetch origin 96a6edb07af44ca5b3c5600e0e662d6308c55fc6 --depth=1
    git reset --hard FETCH_HEAD

    # apply patches
    git apply ../cosmo.patch
fi

# configure
autoconf -f || true

./configure --disable-shared --enable-static\
    --prefix=$COSMOS\
    CFLAGS="-Os"

# run make and/or make install
make -s -j$MAXPROC
make install -s -j$MAXPROC

echo "DONE."
